### ISSUE TITLE
May I ask what are the differences between feature/refactor-electron and feature/update-electron?

### ISSUE THREAD

**Issue by chenzhutian** [singuerinc/overlay#167]
Hi very nice repo. I plan to develop something based on your project. Which branch should I build upon? I see you are working on refactor the repo, but I am not sure which branch is the latest and workable one, https://github.com/singuerinc/overlay/tree/feature/refactor-electron or https://github.com/singuerinc/overlay/tree/feature/update-electron?

Thanks!

**Comment by singuerinc** [comment]
@chenzhutian I failed to update to the latest electron version due to a lot of errors here and there and not having enough time. None of those branches build, so I suggest you to start from master.

**Comment by chenzhutian** [comment]
I see. Thanks and good luck!
