### ISSUE TITLE
Click through the app into the background

### ISSUE THREAD

**Issue by am** [singuerinc/overlay#2]
If the application is in foreground its not possible to click in the transparent parts. It's like the app takes the all screen.

The solution is to put the app in background, but since this is intended to be a 'overlay' it defeats the propose.

**Comment by singuerinc** [comment]
It's also a limitation in a frameless + transparent Electron app. I'm thinking about creating multiple windows for each tool, but it will take some time.

See https://github.com/electron/electron/issues/1335

**Comment by singuerinc** [comment]
Fixed in #32
