### ISSUE TITLE
Consider using NW.js for click-through and transparency

### ISSUE THREAD

**Issue by GnorTech** [singuerinc/overlay#29]
According to https://github.com/electron/electron/issues/1335#issuecomment-397550687 the development of this software is blocked. NW.js supports click-through and transparency well so it could be a valid alternative option: http://docs.nwjs.io/en/latest/For%20Users/Advanced/Transparent%20Window/#click-through-windows-and-mac

**Comment by etisdew** [comment]
As a snippet from my working application licensed under the agplv2.

Consider moving up to electron@latest currently 3.0.0. This provides an alternative interface for the window shape api. However I did not need it. I understand that this might just be a platform specific issue.

```
app.on('browser-window-blur', ()  => { chat_window.setIgnoreMouseEvents(true); });
app.on('browser-window-focus', () => { chat_window.setIgnoreMouseEvents(false); });
```

**Comment by singuerinc** [comment]
@GnorTech I managed to fix this bug with the help of @andens
Thanks a lot for talk about NW.js
I will take a look at it in my next App.

**Comment by etisdew** [comment]
Well I'm really glad to hear you got it! :fire:
