### ISSUE TITLE
Submit the app to Electron Apps

### ISSUE THREAD

**Issue by singuerinc** [singuerinc/overlay#37]
https://github.com/electron/apps/blob/master/contributing.md

**Comment by houllette** [comment]
@singuerinc I can take a shot at this

**Comment by houllette** [comment]
Pull request placed with Electron Apps repo, see: https://github.com/electron/apps/pull/834

**Comment by singuerinc** [comment]
@houllette great!
The building is failing in the CI, I thinks is because the image is too small, you can take this one:
https://github.com/singuerinc/overlay/blob/master/resources/icons/256x256.png

**Comment by houllette** [comment]
Perfect! I didn't even see the larger icon, thanks! I got that pushed, hopefully it'll build now

**Comment by singuerinc** [comment]
Done in https://github.com/electron/apps/pull/838
